# Generated by Django 4.2.4 on 2023-09-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0003_rename_yean_student_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contacton',
            new_name='contactno',
        ),
    ]
