# Generated by Django 4.2.4 on 2023-09-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0004_rename_contacton_student_contactno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='userid',
        ),
    ]
