# Generated by Django 4.2.4 on 2023-08-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departament',
            new_name='department',
        ),
    ]
